# Generated by Django 3.2 on 2022-02-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0025_alter_category_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='brand_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
